### ISSUE TITLE
itglue.Organization.filter name search fails with special characters

### ISSUE THREAD

**Issue by dahifi** [b-loyola/itglue-py#7]
Is there a special syntax for customers w/ commas or hyphens in their name? I get empty set for results. 

Also, is there a syntax for wildcard matches? I looked at the API docs and the source code, but couldn't find a way to do it.

**Comment by b-loyola** [comment]
There is currently a bug in the IT Glue API which prevents organizations with commas in their names from being filtered, because the comma is the filter separator so the API thinks it's two separate organizations. The workaround there is to filter by ID instead. I don't believe there is an issue related to hyphens but I might just not be aware of it.
Unfortunately as far as I know the API currently does not support wildcard searches.

I suggest opening a support ticket with IT Glue  at support@itglue.com to be notified when this bug is fixed.

**Comment by b-loyola** [comment]
Note that this has been resolved by escaping commas with a backslash. For more info see https://support.itglue.com/hc/en-us/articles/360004934397-Sorting-and-filtering-in-the-IT-Glue-API
